<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=1050, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="./css/style.css">

    <title>HOME PAGE</title>
</head>
<body>
    <div class="wrapper">
        <div class="wrapper__content">
            <header class="header">
                <div class="container header__container">
                    <div class="logo header__logo">
                        <a href="/" class="logo__link">PHP-MVC</a>
                    </div>
                    <div class="menu header__menu">
                        <ul class="menu__list">
                            <?php if(!\Core\Auth::user()){ ?>
                                <li class="menu__el">
                                    <a href="/login" class="menu__link">Log In</a>
                                </li>
                                <li class="menu__el">
                                    <a href="/registration" class="menu__link">Registration</a>
                                </li>
                            <?php } else { ?>
                                <li class="menu__el">
                                    <a href="/logout" class="menu__link">Log Out</a>
                                </li>
                                <li class="menu__el">
                                    <a href="/message/create" class="menu__link">Create Message</a>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </header>

            <div class="container container--blog">
                <div class="blogs">
                    <?php
                    foreach ($blogs as $blog) {
                        echo $blog;
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</body>
</html>