<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="<?php echo getPath('css/style.css') ?>">

    <title>HOME PAGE</title>
</head>
<body>
<div class="wrapper">
    <div class="wrapper__content">
        <header class="header">
            <div class="container header__container">
                <div class="logo header__logo">
                    <a href="/" class="logo__link">PHP-MVC</a>
                </div>
                <div class="auth header__auth">
                    <ul class="auth__list">
                        <li class="auth__el">
                            <a href="/login" class="auth__link">Log In</a>
                        </li>
                        <li class="auth__el">
                            <a href="/registration" class="auth__link">Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="container container--user">
            <main class="main">
               <h2 class="main__header">Страница пользователя <?php echo $user->name ?></h2>

                <div class="user-data">
                    <div class="user-data__row">
                        <div class="user-data__cell">Имя</div>
                        <div class="user-data__cell"><?php echo $user->name ?></div>
                    </div>
                    <div class="user-data__row">
                        <div class="user-data__cell">Email</div>
                        <div class="user-data__cell"><?php echo $user->email ?></div>
                    </div>
                    <div class="user-data__row">
                        <div class="user-data__cell">Дата регистрации</div>
                        <div class="user-data__cell"><?php echo $user->created_at ?></div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>
</body>
</html>